project:
  type: website
  output-dir: docs

website:
  title: 'Kalyan "Arjun" Lakshmanan'
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/kalymaan
      - icon: twitter
        href: https://twitter.com/kalymaan
      - icon: linkedin
        href: https://www.linkedin.com/in/kalyanlakshmanan/
format:
  html:
    theme: slate
    css: styles.css



